PR for #3: Regression on years greater than 1960
shrishj/template pull request #4
Opened 2023-10-25 23:08 UTC by shrishj

I have modified code in the analysis folder [~/analysis/code/analyze_data.py](https://github.com/shrishj/template/blob/54ee1328331ab773e55f5ae922870c099ce12e57/analysis/code/analyze_data.py) so that we create a new table to hold our values in [analysis/output/regression_subset.csv](https://github.com/shrishj/template/blob/54ee1328331ab773e55f5ae922870c099ce12e57/analysis/output/regression_subset.csv). This follows from the [Practice Task Instructions](https://github.com/gslab-econ/lab-manual/wiki/Practice-Task).

I have assigned @ShiqiYang2022, @jc-cisneros, and @snairdesai to review this request.

Closes #3

2023-10-25 23:23 UTC, ShiqiYang2022 commented on data/output/chips_sold.pdf
@shrishj I think you should also add code to include the paper into this `.pdf`, thanks!

2023-10-25 23:23 UTC, ShiqiYang2022 requested changes
Thanks @shrishj! I have some requests for you to change the code according.

2023-10-25 23:24 UTC, ShiqiYang2022 commented on paper_slides/output/paper.pdf
@shrishj I think you should also add code to include the table into this `.pdf`, thanks!

2023-10-25 23:58 UTC, shrishj commented on paper_slides/output/paper.pdf
Hi @ShiqiYang2022 , here is my changed version: [1675c2d](https://github.com/shrishj/template/pull/4/commits/1675c2dea78fa321cbb42c30f9399ee98e1fcf3f)

2023-10-26 00:01 UTC, ShiqiYang2022 approved these changes
I think the change looks good so I am approving. It could be better if we modify the name of the table according, but this is trivial. Thanks for the work @shrishj!

2023-10-26 00:03 UTC, merged